### ISSUE TITLE
bw-viewmediator does not resolve all sections

### ISSUE THREAD

**Issue by njam3** [bigwheel-framework/bigwheel#1]
The destroy function is not called unless all items in the array fully animate out and call the onComplete. This poses a problem for headers/footers that need to stay on the page. The solution may be to define an object that does always call animateIn/Out unless it is actually removed from the array.

**Comment by MikkoH** [comment]
The more I look at this issue I'm not sure it's something that should be fixed.

**Comment by njam3** [comment]
I think this is remedied by passing the route into all functions, it enables us to conditionally call the proper functions, i.e. only destroy the header if we go to the landing page.
