### ISSUE TITLE
Wrong bw-router version in package.json dependencies

### ISSUE THREAD

**Issue by Dansuncoin** [bigwheel-framework/bigwheel#13]
Hello,

I wanted to give a try to bigwheel but I can't make it works for 2 hours :( (and I feel so lame...)

In fact, the last version of bw-router doesn't seem to work with your code sample so I have to move backward to the release 1.1.3 and it solves all my problems !

Maybe you should use a tilde(~) instead of a caret(^) in the dependencies of your package.json file ;)
"dependencies": {
    "bw-router": "~1.1.3",
    "bw-viewmediator": "^2.0.0",
    "bw-vm": "^2.0.3",
    "dom-event": "git://github.com/mikkoh/dom-event"
  }

Otherwise, you did an awesome work!
Thanks for sharing it !

**Comment by MikkoH** [comment]
My bad. I can look into this in like two weeks. My second daughter was born on Friday.

This issue might be caused by the fact that I've been working on the next version of bigwheel where it'l be able to handle subroutes better.

You should be able to grab that version from `npm i bigwheel@next`

**Comment by MikkoH** [comment]
Feel free to make a pull request or test out @next. I don't mind pushing that live if it's working. It just hasnt been tested on a project yet so I've been reluctant.

**Comment by Dansuncoin** [comment]
Hey ! That's a good news :)
Congratulations !
Javascript can wait ;)

Thanks for the @next version.
Cheers.
