### ISSUE TITLE
Setting duplicate to true causes route to be called twice

### ISSUE THREAD

**Issue by wongbsn** [bigwheel-framework/bigwheel#15]
When setting duplicate to true and using framework.go, the route will be called twice, finishing a full cycle. This does not happen when you go directly using the address bar.

Init
Animate In
Init
Animate Out
Destroy
Animate In

**Comment by baptistebriel** [comment]
I'm running into this issue as well, but for me it seems like the `destroy` method is called right after `init` — even before init's `done` has been called.

Here's the logs:

section init
section destroy
section init
section animateIn

**Comment by MikkoH** [comment]
@baptistebriel can you add a section name so it's easier to trace whats going on eg.
Section B Init
Section A animateOut
Section B animateIn
...

Also @wongbsn same deal. Sorry guys... I've been swamped.

**Comment by baptistebriel** [comment]
sorry, that was the exact same section.
for example, if the first page is `/home`, calling `framework.go('/section/one');` will do:

section one init
section one destroy
section one init
section one animateIn

I only console logged the section that has `duplicate: true`, because regular sections are working fine.

**Comment by MikkoH** [comment]
Is your section an `Object` or a `Function`.

**Comment by baptistebriel** [comment]
The `prototype` is an `Object`, basically this: https://github.com/baptistebriel/biggie/blob/gh-pages/assets/js/sections/section.js

**Comment by wongbsn** [comment]
I fixed this issue last week. Do you have the lastest version?

**Comment by MikkoH** [comment]
@wongbsn yeah I remember you doing a PR that @njam3 merged but I wasn't 100% sure :+1: 

@baptistebriel please update to the newest version of `bigwheel` and mark this as closed if we're good.

If not then it just might be a versioning issue with router and `bigwheel`. (thats an easy fix)

**Comment by baptistebriel** [comment]
Yay! Thanks @wongbsn & @MikkoH :) I don't have the rights to close the issue, could someone do it?
