### ISSUE TITLE
Duplicate route

### ISSUE THREAD

**Issue by MadebyAe** [bigwheel-framework/bigwheel#16]
Hello guys, I defined this route: `/section/:title/` but when I browse from `/section/staff/` to `/section/random/` nothing happens. 

Also I trying with `duplicate: true` but never destroy the previous instance.

**Comment by MikkoH** [comment]
Hmmm... This should work when you have `duplicate: true`.

Are you sure the callback is being called in `animateOut`. `destroy` will not be called until this callback has been called.

**Comment by MadebyAe** [comment]
Yes take a look... https://gist.github.com/MadebyAe/278e963f7c4e30c24b1f

**Comment by MadebyAe** [comment]
When I run `npm test` everything seems OK.
So `duplicate: true` is only available with `subroutes`?

Thanks.

**Comment by baptistebriel** [comment]
I think `subroutes` are not implemented yet, see #3 

Maybe make sure to `console.log` everytime you pass `done` from one function to another?

I made a quick example with `duplicate: true` and it seems to be working fine: https://github.com/baptistebriel/biggie

**Comment by MikkoH** [comment]
`subroutes` maybe in. I haven't been able to review. See what happened is I had deployed `subroutes` and you could use them via `npm i bigwheel@next` but unfortunately what happned is the router was upgraded using a minor version bump which messed up the current "stable" version of `bigwheel`. (thats what i get for trying to be fancy)

Anyway. While I was on parental leave (daughter was born 3 weeks ago) there was an issue @njam3 may have pushed `subroutes` live to fix that issue.

**Comment by MikkoH** [comment]
As you can see https://github.com/bigwheel-framework/bigwheel/blob/master/index.js#L122 is there but I'm not sure if it's on npm.

**Comment by MadebyAe** [comment]
@baptistebriel Thanks. 
Lovely `Utils function`BTW.

**Comment by MikkoH** [comment]
@baptistebriel Nice one with `biggie` internally we have a yeoman generator we've been working on for a bit. Not sure if we'll open source it someday.

It's a big project and is very specific to our workflow.

**Comment by baptistebriel** [comment]
Thanks for pointing this out @MikkoH, and yes I was thinking about the stable version. I think we already spoke a bit about the Yeoman generator, and no problem for not open sourcing it. It's good to keep bigwheel very simple without too much things aside.

@MadebyAe Thanks! We all have our own way of using bigwheel, therefore it can be expanded in very different ways. It's interesting to see what other developers can do of it.

**Comment by MikkoH** [comment]
;) @baptistebriel I love this sentence "We all have our own way of using bigwheel, therefore it can be expanded in very different ways"

**Comment by MadebyAe** [comment]
Only fails when using ES6 `Class`

**Comment by MadebyAe** [comment]
Fixed! My bad.

Thanks @MikkoH @baptistebriel  :)
