### ISSUE TITLE
overlap:false doesn't work

### ISSUE THREAD

**Issue by wongbsn** [bigwheel-framework/bigwheel#21]

**Comment by baptistebriel** [comment]
Hmm, it works (I think) because I'm actually using it for a current project.
w/ theses versions:

```javascript
"dependencies": {
    "bigwheel": "^3.0.1",
    "bw-router": "~1.1.3",
    "bw-viewmediator": "^2.0.0",
    "bw-vm": "^2.0.0",
}
```

**Comment by wongbsn** [comment]
Yes, it is working as expected. I thought it would not call the init until the animOut was done.
