### ISSUE TITLE
on('route' cb) Callback function being called twice.

### ISSUE THREAD

**Issue by BrendanNeufeld** [bigwheel-framework/bigwheel#22]
```framwork.on('route', function(data){
// I get called twice!
});```

`bw-anlaytics` uses this callback and consequently two analytics calls are being made.

**Comment by mikkoh** [comment]
@BrendanNeufeld is this for routes with `duplicate` true?

**Comment by njam3** [comment]
@BrendanNeufeld Do you have any more info on this one? I just tried it on a newly created project and it only got called once per route change.

**Comment by BrendanNeufeld** [comment]
It was a long time ago. It may have been with a previous version of BW?

**Comment by njam3** [comment]
@BrendanNeufeld Cool, I know we've made a number of fixes in that regard, but if it comes back, please reopen this issue.
