### ISSUE TITLE
Better sub route handling

### ISSUE THREAD

**Issue by mikkoh** [bigwheel-framework/bigwheel#3]
Currently one route is tied so heavily to one section it causes issues.

For instance:
```javascript
{

	routes: {

		'/gallery': gallerySection,
		'/gallery/:item': galleryItem
	}
}
```

If you went to the route `'/gallery/1'` the `gallerySection` would never resolve.

A better way to do it might be to do the following:
```javascript
{
	routes: {

		'/gallery': {

			section: gallerySection,

			routes: {

				'/gallery/:id': {

					section: galleryItem
				}
			}
		}
	}
}
```

This would allow the framework to know that it needs to continue resolving routes potentially for a section.

**Comment by MikkoH** [comment]
It might be better to do it so sub sections can create their own sub frameworks. A gallery is a good example. It could look something like:

```
var galleryFrameWork = framework.sub( '/gallery' , function( done ) {

  done( {

    routes: {

      '/:galleryId': someSection // would match "#!/gallery/10"
    }
  });
});
```

It would also be good to think of passing the framework that caused the section to come in to be passed in the init function.
