### ISSUE TITLE
using bigwheel with babelify@7.2.0

### ISSUE THREAD

**Issue by baptistebriel** [bigwheel-framework/bigwheel#31]
Hi,

So I'm trying to use bigwheel with the latest babel: `babelify@7.2.0` & `babel-preset-es2015@6.5.0`
Also have this in `package.json`:
```
"browserify": {
  "transform": [
    [
      "babelify",
      {
        "only": "assets/js/",
        "presets": [
          "es2015"
        ]
      }
    ]
  ]
}
```
... and as well a `.babelrc` file, etc... basically the configuration on another module of mine 😬

And I have this error from the initSection:

![screen shot 2016-02-09 at 20 04 41](https://cloud.githubusercontent.com/assets/2464663/12927617/56f05688-cf69-11e5-9d46-99c8415c4276.png)

I'm wondering if this is somehow because of using babel along bigwheel or if I'm just doing something wrong. It works if I'm using `babelify@6.4.0`. This babel thing is slowly but surely driving me nuts 🙃

Anyway if you have any idea!

**Comment by mikkoh** [comment]
What does your section look like? Is it a function or an Object or?

**Comment by baptistebriel** [comment]
`initSection` appears as _esModule, an object with `defaults` inside. Is an export or transform done bad here? I'm using ES6 class.

```
class Preloader {
	
	constructor(onComplete) {
		
		this.preloaded = onComplete
	}
	
	// ...
}

export default Preloader
```

**Comment by mikkoh** [comment]
Can you show me how you define routes?

We've run into issues with babel where if you use `export` and then later `require` instead of `import` you get an `Object` instead of a `Function`

**Comment by baptistebriel** [comment]
Yes, I think it might be the case here..
Here's how I define routes/initSection:

```javascript
import bigwheel from 'bigwheel'

const framework = bigwheel((done) => {
	done({
		overlap: false,
		initSection: require('./sections/preloader'),
		routes: require('./routes')
	})
})

export default framework
```

```javascript
const routes = {
	'/': require('./sections/home'),
	'/home': { section: require('./sections/home') },
	'/about': { section: require('./sections/about') },
	'/section/:id': { section: require('./sections/section'), duplicate: true }
}

export default routes
```

**Comment by mikkoh** [comment]
Yeah. For now I'm using `CommonJS` `require` and `module.exports` cause I've read that Babel's implementation of `import` `export` is quite non-standard.

Hey if this fixes this issue do you mind Closing this issue? If not I can still try to figure it out with you.

**Comment by baptistebriel** [comment]
Sure, as this is not bigwheel related in any kind. Will try to fix this and will let you know on Slack / Twitter if I have any issues :) Thanks a lot @mikkoh !

**Comment by baptistebriel** [comment]
It did worked using `module.exports` instead of `export defaults`
Still using `import` instead of `require` tho. Thank you a lot @mikkoh ! 🍻
