### ISSUE TITLE
animateOut of sub route sometimes gets called twice (and no animateIn of new sub route)

### ISSUE THREAD

**Issue by baptistebriel** [bigwheel-framework/bigwheel#32]
Hi!

I just had an issue while trying out sub routes: looks like sometimes, the `init` function will get called but no `animateIn`. Instead, it's trying to call `animateOut` of **the previous sub route**. See this screenshot:

![screen shot 2016-02-27 at 16 50 13](https://cloud.githubusercontent.com/assets/2464663/13373831/2fd81e20-dd72-11e5-8892-3ae80717e91f.png)

I tried to add `duplicate: true`, made sure I didn't forgot a `done` somewhere..
You can try it live [here](http://biggie.bbriel.me/). I also pushed it to a [new branch](https://github.com/baptistebriel/biggie/tree/subroutes) if you want to see the source code.

Any ideas would be much appreciated.. Thanks! 😊

**Comment by mikkoh** [comment]
Hmmm... This sounds like `onComplete` wasn't called for `init` can you confirm? Although it's wierd that the `animateOut` got called. Sub routes are something that @njam3 implemented in the latest build. @njam3 have you seen this?

**Comment by baptistebriel** [comment]
Yes, `onComplete` doesn't get called. Strange thing is that I do call `done` on `init` ([here](https://github.com/baptistebriel/biggie/blob/subroutes/assets/js/sections/sub.js#L48)) but `animateIn` doesn't get called; otherwise we could have had the `console.log`.

**Comment by mikkoh** [comment]
Me or @njam3 will take a look at this when we get a chance. Thanks for the issue.

**Comment by njam3** [comment]
@baptistebriel Did some testing on my own build and didn't notice anything. I'm working with your repo now and I'll let you know what i find.

**Comment by baptistebriel** [comment]
@mikkoh @njam3 Thank you for the fast replies! 👍

I basically followed up the instructions from [this commit](https://github.com/bigwheel-framework/bigwheel/commit/b797ee59ee50bf0501d6677a4750d047ac90d981) as the documentation doesn't tell about sub routes yet. But maybe I forgot something?

Let me know if you think the issue comes from my own code. I'll dig into that again this week-end.

**Comment by njam3** [comment]
@baptistebriel Narrowed this down to an issue in bw-vm and I've pushed a fix for it in bw-vm@2.1.3. If you still are having this issue, please reopen this ticket. And thanks for helping us make this project better :+1:

**Comment by baptistebriel** [comment]
Works like a charm — thank you a lot @njam3! 🎉
