### ISSUE TITLE
Routing not working when reload the page

### ISSUE THREAD

**Issue by Pau1fitz** [bigwheel-framework/bigwheel#36]
I am following the guidance on this page - https://github.com/bigwheel-framework/documentation/blob/master/quickstart.md

I have set up my routes like this 

`routes: {
     	'/': Section,
     	'/about': About
    }`

when I go to the browser and try and use `http://localhost:8000/#!about` this doesn't work. Is there something that I am missing?

does anyone know why this doesn't work and what I may need to change?

See[ full code here](https://jsfiddle.net/w8ymww7c/2/)

Thanks for the help! is this the correct place to raise this issue or is a gist better?

**Comment by mikkoh** [comment]
I believe by default `bigwheel` doesn't use hash bang urls anymore. I think by default it uses push state. (no hash bang added)

Just set `pushState: false` if you want to use hash bang urls.

You can see an example of that here:
https://github.com/bigwheel-framework/bw-router/blob/master/README.md

Or if you set your local dev server to use push states you should be able to use cleaner urls such as `http://localhost:8000/about`

**Comment by Pau1fitz** [comment]
thanks @mikkoh  

does that mean I need to go into the bw-router file and change this?

**Comment by baptistebriel** [comment]
It should work on `http://localhost:8000/about` with push states by default, as @mikkoh said previously. If you add `pushState: false` in your routes definition then it should work on `http://localhost:8000/#!/about` using hash bangs.

**Comment by Pau1fitz** [comment]
@mikkoh  and @baptiste. i think it must be the way my server is set up. I will try and get my grunt server to allow this to work.

**Comment by Pau1fitz** [comment]
@mikkoh  and @baptistebriel  went for the option of using hash bang urls for now and it works great, thanks!

**Comment by mikkoh** [comment]
Yeah using hash bang urls to start out with is a great option and then when you go to production you can switch to push state.
