### ISSUE TITLE
animateIn animateOut not working as expected and overlapping

### ISSUE THREAD

**Issue by Pau1fitz** [bigwheel-framework/bigwheel#37]
In order to populate the content I am making GET requests to different html files, and populating the page. This is all working well. 

However, I am having difficulties with the animateIn and animateOut functions.

These animations are overlapping. I have added `overlap:false` to my code, but this doesn't seem to prevent the overlapping of animations. The init function of the next route gets called before the animateOut has finished. Is this the expected behaviour?

I am trying to Tween multiple elements, and am just calling `onComplete: done` on the last Tween. Perhaps I need to take a different approach as I am tweening multiple elements. I have read through the closed issues on the project aswell, which had an issue related to the same thing, but still can't find how to fix this.

I have attached my code in this jsfiddle - https://jsfiddle.net/d27xy7jh/1/. The html is just a mock html that I make a GET request to, to give an idea. 

Hopefully it is clear follow what I mean. If any more info is required let me know.

**Comment by Pau1fitz** [comment]
I have managed to get it working by following the guidance [here](https://github.com/bigwheel-framework/documentation/blob/master/sections-init.md) to hide the elements in the `init()` section and then displaying them again in the `animateIn()` function.

I was confused and thought that the `animateOut()` function was called before the `init()` function of the new route.

**Comment by mikkoh** [comment]
Glad you figured it out. Make sure to show me what you've built when you're done.

**Comment by Pau1fitz** [comment]
will do!
