### ISSUE TITLE
404 Redirect Section Not Working

### ISSUE THREAD

**Issue by njam3** [bigwheel-framework/bigwheel#9]
I do no think the 404 section works anymore, simply setting it up to redirect to the landing page did not work.

'/': {section: []},
'404': '/'

**Comment by MikkoH** [comment]
Yeah I'm not sure redirects have ever worked for 404. I was actually just testing it the other day but forgot to make an issue.

I think passing a section should work. So if you require redirects immediately you could create a dummy section that just redirects.

Thanks for bringing this up.
